### PR TITLE
Display query arguments into query logger view

### PR DESCRIPTION
**Pull request by maximebeaudoin**
It would be interesting to see the arguments SQL queries in the tables of queries. However, I don't know if it would be better to add a column in the table instead.

### CODE REVIEW

**Comment by daylerees** [comment]
Hi there! Do the query arguments not appear within the query string for you? Laravel replaces the bindings before the query event is fired.

**Comment by maximebeaudoin** [comment]
No, i also dump queries into a log file since Laravel 4.0 and i have never seen arguments in queries. Currently i use Laravel 4.2.9.

query-screenshot

**Comment by maximebeaudoin** [comment]
I have take a look at https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Connection.php#L715 and i don't see where the bindings is replaced in the query.

**Comment by daylerees** [comment]
Thanks man, I'll probably replace them myself then. Would be nice to have them in the query for clarity I think :)

**Comment by maximebeaudoin** [comment]
Agree, would be MUCH better.

**Comment by daylerees** [comment]
Could you put it in the extra column mate? I'll merge this until I get time to replace full bindings.

**Comment by maximebeaudoin** [comment]
Done, i added the style `word-break: break-all;` because sometime arguments list are very long and i don't want to break the table.

**Comment by daylerees** [comment]
Great, thanks :)

**Pull request merged**
