### PR TITLE
Fix redirects

### PR DESCRIPTION
**Pull request by barryvdh**
1. Don't append data to redirects.
2. Don't echo output, that kills the headers.

### CODE REVIEW

**Comment by barryvdh** [comment]
And you should probably try to inject it in the body, instead of just appending it. And when you use a Middleware you could probably catch errors as well (not sure if that is possible with After filters in the latest version)

**Comment by daylerees** [comment]
That makes sense. Thanks man. Surprised the body of the request interferes with the header though.

**Comment by barryvdh** [comment]
Hmm, probably when you echo, the data is ouputted before the headers are sent properly. Same reason you should echo stuff in controllers, but just return the content. Same goes for filters etc.

**Comment by daylerees** [comment]
Guess so. Thanks dude :)

**Pull request merged**
